#!/bin/bash

# skript 1 kuni 10 paarisarvud (kaasaarvatud) vaartuse kasutades
# for tsyklit

summa=0

for (( arv=1; arv<11; arv++))
do
	jaak=$((arv % 2))
	if [ $jaak -eq 0 ]; then
		summa=$(($summa + $arv))
	fi
done
echo "Arvude vahemikus 1 kuni 10 (kaasaarvatud) paarisarvude summa on: $summa"


