#!/bin/bash

# skript valjastab esimesed 20 arvu ning kas need on algarvud voi mitte

for (( arv=1; arv<21; arv++ ))
do
    jagaja=2
    jaak=$((arv % jagaja))

    while [[ $jaak -ne 0 && $jagaja -lt $arv ]]
    do
        jagaja=$((jagaja + 1))
        jaak=$((arv % jagaja))
    done
    if [ $arv -eq $jagaja ]; then
        echo "$arv - on algarv"
    else
	echo "$arv - ei ole algarv"
    fi
done
